name: smart_home
version: 1.0.0+1
publish_to: none
description: Flutter Home UI.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  relative_scale: ^2.0.0
#  liquid_pull_to_refresh: 3.0.1
  flutter: 
    sdk: flutter
  flutter_any_logo: ^1.1.1
  crypto_market: ^0.0.3

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: GilroyFont
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
          weight: 600
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
          weight: 600
        - asset: assets/fonts/gilroy/Gilroy-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
          weight: 600
        - asset: assets/fonts/gilroy/Gilroy-Thin.ttf
          weight: 200
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/gilroy/Gilroy-Light.ttf
          weight: 300
  assets:
    - assets/icons/
    - assets/fonts/


